# Generated by Django 5.2.5 on 2026-01-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0002_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
