# Generated by Django 5.2.5 on 2026-01-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0004_contact"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contact",
            table=None,
        ),
    ]
