# Generated by Django 5.2.5 on 2026-01-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0005_alter_contact_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
